# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [126]:
from scipy import stats 
import numpy as np
from    scipy.stats             import  ttest_1samp,ttest_ind, wilcoxon, ttest_ind_from_stats
import  scipy.stats             as      stats  
from    statsmodels.stats.power import  ttest_power
import  matplotlib.pyplot       as      plt

In [25]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [8]:
print("The Mean of GPU1 is ", np.mean(GPU1))
print(len(GPU1))
print(len(GPU2))

print(" The Mean of GPU 1 is not Equal to Zero basis which we conclude to reject the NUll Hypothesis.")

The Mean of GPU1 is  10.333333333333334
15
15
 The Mean of GPU 1 is not Equal to Zero basis which we conclude to reject the NUll Hypothesis.


## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [9]:
#### Null hypotheis : mu1- mu2 = 0
#### Alternate Hypothesis : mu1 - mu2 is not equal to 0 

print(" The mu1 of the data set GPU 1 is ",np.mean(GPU1))
print(np.std(GPU1))
print(" The mu2 of the data set GPU 2 is ",np.mean(GPU2))
print(np.std(GPU2))
t_statistic, p_value  =  stats.ttest_rel(GPU1,GPU2)
print( p_value)
print("We consider the value of Aplha is 0.05% and the Sample Size is less than30 and the standard deviation is not known .")
print(" Result :As the P value is less than Aplha which is 5% we can conclude that the as the P valueis less  than Aplha we therefore reject the null hypothesis and accept the alternate hypothesis .which states that there is significance difference in both the data sets")

 The mu1 of the data set GPU 1 is  10.333333333333334
1.1352924243950933
 The mu2 of the data set GPU 2 is  11.466666666666667
1.1469767022723503
0.02346537162637542
We consider the value of Aplha is 0.05% and the Sample Size is less than30 and the standard deviation is not known .
 Result :As the P value is less than Aplha which is 5% we can conclude that the as the P valueis less  than Aplha we therefore reject the null hypothesis and accept the alternate hypothesis .which states that there is significance difference in both the data sets


## Question 3

He is trying a third GPU - GPU3.

In [5]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])
len(GPU3)

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

15

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [10]:
#### Null hypotheis : mu1- mu2 = 0
#### Alternate Hypothesis : mu1 - mu2 is not equal to 0 
t_statistic, p_value  =  stats.ttest_rel(GPU1,GPU3)
print( p_value)
print(" The mu3 of the data set GPU 3 is ",np.mean(GPU3))

print("We consider the value of Aplha is 0.05% and the Sample Size is less than30 and the standard deviation is not known.")
print("Result :As the P value is more than Aplha which is 5% we can conclude that the as the P value is more than Aplha we therefore Failed to reject the null hypothesis , which states that there is  no significance difference in both the data sets")

0.13520778142018045
 The mu3 of the data set GPU 3 is  11.066666666666666
We consider the value of Aplha is 0.05% and the Sample Size is less than30 and the standard deviation is not known.
Result :As the P value is more than Aplha which is 5% we can conclude that the as the P value is more than Aplha we therefore Failed to reject the null hypothesis , which states that there is  no significance difference in both the data sets


## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [58]:
import numpy as np
import pandas as pd
from scipy.stats import levene


e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [59]:
### Assuming that the aplha value is 5% 
###Null Hypothesis is that all the samples have the same equal variances mu1=mu2=mu3.
###Alternate hypotheis is that there is a significance difference in variancesmu1is not equal to mu2 is not equal to mu3.

print("The lenght , mean and std of array e1 is ",len(e1),np.mean(e1),np.std(e1,ddof=1))
print("The lenght , mean and std of array e2 is ",len(e2),np.mean(e2),np.std(e2,ddof=1))
print("The lenght , mean and std of array e3 is ",len(e3),np.mean(e3),np.std(e3,ddof=1))

print(levene(e1,e2,e3))

print(" As the P value is more than 5%, there fore we failed to reject the null hypothesis which states that all the samples have the same equal variances")    
    

The lenght , mean and std of array e1 is  4 0.7537925 0.8733555088040227
The lenght , mean and std of array e2 is  4 1.69759475 0.6674627709994392
The lenght , mean and std of array e3 is  4 0.7444685 0.4726609560389632
LeveneResult(statistic=2.6741725711150446, pvalue=0.12259792666001798)
 As the P value is more than 5%, there fore we failed to reject the null hypothesis which states that all the samples have the same equal variances


## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [69]:
### Null Hypothesis is mu1=mu2=mu3.(There is no signifance difference btwn the data sets.)
### Alternate Hypothesis is atleast one of the mu value is different from the other which
                            ### states that there is a signifance differnce btwn the data sets)
import pandas as pd
import statsmodels.api         as     sm
from   statsmodels.formula.api import ols

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

print("The lenght , mean and std of array e1 is ",len(e1),np.mean(e1),np.std(e1,ddof=1))
print("The lenght , mean and std of array e2 is ",len(e2),np.mean(e2),np.std(e2,ddof=1))
print("The lenght , mean and std of array e3 is ",len(e3),np.mean(e3),np.std(e3,ddof=1))




The lenght , mean and std of array e1 is  4 0.7537925 0.8733555088040227
The lenght , mean and std of array e2 is  4 1.69759475 0.6674627709994392
The lenght , mean and std of array e3 is  4 0.7444685 0.4726609560389632


In [75]:
array_df = pd.DataFrame()

df1            = pd.DataFrame({'e': '1', 'array_data':e1})
df2            = pd.DataFrame({'e': '2', 'array_data':e2})
df3            = pd.DataFrame({'e': '3', 'array_data':e3})

array_df = array_df.append(df1) 
array_df = array_df.append(df2) 
array_df = array_df.append(df3) 

In [76]:
array_df.head()

e  array_data
0  1     1.59544
1  1     1.41973
2  1     0.00000
3  1     0.00000
0  2     1.43380

In [84]:
import statsmodels.api         as     sm
from   statsmodels.formula.api import ols

mod = ols('array_data ~ e', data = array_df).fit()
aov_table = sm.stats.anova_lm(mod, typ=2)
print(aov_table)

print("As the value of P is more than the value of Aplha the statistical decision is to failed to reject the null hypothesis at Aplha is at 5%")

            sum_sq   df         F    PR(>F)
e         2.399066  2.0  2.513576  0.135746
Residual  4.294994  9.0       NaN       NaN
As the value of P is more than the value of Aplha the statistical decision is to failed to reject the null hypothesis at Aplha is at 5%


## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

Type 1 and Type II errors cannot happen at the same time .

Type I error occurs only when H0 is True
Type II error occurs only when H0 is False . 

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


NUll hypothesis: There is no significance change in the population mean mu1-mu2=0
Alternate Hypothesis: There is a significant change in the population mean mu1-mu2 is not equal to 0.

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [109]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [148]:
dice = np.array([d1, d2, d3, d4, d5, d6]) 
chi_sq_Stat, p_value, deg_freedom, exp_freq = stats.chi2_contingency(dice)
print(" The chi_sq_Stat, p_value, deg_freedom ,contigency",chi_sq_Stat, p_value, deg_freedom,exp_freq)

 The chi_sq_Stat, p_value, deg_freedom ,contigency 23.315671914716496 0.07766367301496693 15 [[ 5.57419355  8.20645161  5.57419355  4.64516129]
 [ 6.50322581  9.57419355  6.50322581  5.41935484]
 [ 6.73548387  9.91612903  6.73548387  5.61290323]
 [ 6.96774194 10.25806452  6.96774194  5.80645161]
 [ 5.34193548  7.86451613  5.34193548  4.4516129 ]
 [ 4.87741935  7.18064516  4.87741935  4.06451613]]


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [162]:
zscore =stats.zscore(dice,axis=1)
print(zscore)
print("The mean of the array before conversion of the zscore values ot the P value",np.mean(zscore))

[[-0.47140452  0.94280904 -1.41421356  0.94280904]
 [ 1.26491106 -0.63245553  0.63245553 -1.26491106]
 [ 0.21055872  1.33353857 -0.07018624 -1.47391105]
 [-0.68313005  1.65903012 -0.09759001 -0.87831007]
 [-1.27017059  1.5011107   0.11547005 -0.34641016]
 [ 0.85518611 -1.58820278 -0.12216944  0.85518611]]
The mean of the array before conversion of the zscore values ot the P value -9.25185853854297e-18


In [160]:
from scipy.special import ndtr as ndtr
p_values = 1 - ndtr(zscore)
print(p_values)
print("The mean of the array after conversion of the zscore values ot the P value",np.mean(p_values))

[[0.68132406 0.17288929 0.9213504  0.17288929]
 [0.10295161 0.73645537 0.26354463 0.89704839]
 [0.41661581 0.09117756 0.52797729 0.92974723]
 [0.75273767 0.04855486 0.53887107 0.81011226]
 [0.89798806 0.06666347 0.45403628 0.63548276]
 [0.19622406 0.94387975 0.54861759 0.19622406]]
The mean of the array after conversion of the zscore values ot the P value 0.5001401174675847


## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [180]:
 ## Creates a normal distribution with a mean value of 100 and std of 30
before= stats.norm.rvs(scale=30, loc=100, size=500)
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [183]:
from scipy.stats             import ttest_1samp,ttest_ind, wilcoxon
from statsmodels.stats.power import ttest_power
import matplotlib.pyplot     as     plt

###Null hypothesis is there is no significant change in the weigths mu1-mu2=0
##Alternate hypothesis is there is a significant change in the weight mu1 is not equal to mu2 

t_statistic, p_value  =  stats.ttest_ind(before,after)
print(p_value)
print("As the pvalue is more than the value of Alpha which is 5% we therefore failed to reject the null hypothesis at this level of significance, where as here we accept the null hypothesis")

0.6610804334184517
As the pvalue is more than the value of Alpha which is 5% we therefore failed to reject the null hypothesis at this level of significance, where as here we accept the null hypothesis
